// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDbLib;

namespace MovieDbLib.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MovieDbLib.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 0,
                            Description = "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
                            Image = "https://image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-09-30",
                            Title = "Venom: Let There Be Carnage"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 0,
                            Description = "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
                            Image = "https://image.tmdb.org/t/p/w500/lr3cYNDlJcpT1EWzFH42aSIvkab.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-09-15",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 0,
                            Description = "Minutes after Laurie Strode, her daughter Karen and granddaughter Allyson left masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with life-threatening injuries, believing she finally killed her lifelong tormentor. But when Michael manages to free himself from Laurie's trap, his ritual bloodbath resumes. As Laurie fights her pain and prepares to defend herself against him, she inspires all of Haddonfield to rise up against their unstoppable monster. The Strode women join a group of other survivors of Michael's first rampage who decide to take matters into their own hands, forming a vigilante mob that sets out to hunt Michael down, once and for all.",
                            Image = "https://image.tmdb.org/t/p/w500/qmJGd5IfURq8iPQ9KF3les47vFS.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-10-14",
                            Title = "Halloween Kills"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 0,
                            Description = "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
                            Image = "https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-08-11",
                            Title = "Free Guy"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 0,
                            Description = "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
                            Image = "https://image.tmdb.org/t/p/w500/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2018-09-28",
                            Title = "Venom"
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 0,
                            Description = "With the help of the \"Dragon Sin of Wrath\" Meliodas and the worst rebels in history, the Seven Deadly Sins, the \"Holy War\", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the \"Lion Sin of Pride\" Escanor's life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.",
                            Image = "https://image.tmdb.org/t/p/w500/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
                            Language = "ja",
                            Length = 100,
                            ReleaseDate = "2021-07-02",
                            Title = "The Seven Deadly Sins: Cursed by Light"
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = 0,
                            Description = "The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.",
                            Image = "https://image.tmdb.org/t/p/w500/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-10-01",
                            Title = "The Addams Family 2"
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = 0,
                            Description = "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
                            Image = "https://image.tmdb.org/t/p/w500/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-07-22",
                            Title = "Snake Eyes: G.I. Joe Origins"
                        },
                        new
                        {
                            Id = 9,
                            AgeRestriction = 0,
                            Description = "Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony \"The Cannibal\" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.",
                            Image = "https://image.tmdb.org/t/p/w500/jxdKa1467pktAILLbfw6kZyQlbW.jpg",
                            Language = "es",
                            Length = 100,
                            ReleaseDate = "2021-10-01",
                            Title = "Matando Cabos 2: La Máscara del Máscara"
                        },
                        new
                        {
                            Id = 10,
                            AgeRestriction = 0,
                            Description = "The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.",
                            Image = "https://image.tmdb.org/t/p/w500/vFIHbiy55smzi50RmF8LQjmpGcx.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2020-08-04",
                            Title = "Deathstroke: Knights & Dragons - The Movie"
                        },
                        new
                        {
                            Id = 11,
                            AgeRestriction = 0,
                            Description = "Ahead of a promotion, a police chief becomes entangled in a deadly incident and uncovers an intrigue fueled by grudge that threatens his colleagues.",
                            Image = "https://image.tmdb.org/t/p/w500/xSqtHT2DWbWBZ4dUvvMs6z1OfFK.jpg",
                            Language = "tr",
                            Length = 100,
                            ReleaseDate = "2021-10-08",
                            Title = "Grudge"
                        },
                        new
                        {
                            Id = 12,
                            AgeRestriction = 0,
                            Description = "In the near future on a colony of state-of-the-art robots, a private investigator is hired by the colony's creator to bring his missing daughter home.",
                            Image = "https://image.tmdb.org/t/p/w500/wIm5S6Blkb0qDMTGVu80VWSrQV1.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-09-03",
                            Title = "Zone 414"
                        },
                        new
                        {
                            Id = 13,
                            AgeRestriction = 0,
                            Description = "In the Forest of Okoya, Koko is a feral child who has been raised as a Pokémon by the Mythical Pokémon Zarude. Koko has grown up never doubting that he is a Pokémon even though he can't really use any sort of moves. Ash Ketchum and Pikachu meet Koko and help him protect the Great Tree from the crooked scientist Dr. Zed.",
                            Image = "https://image.tmdb.org/t/p/w500/vGcHyV9s1N2I7bJLSBODvqHTYLL.jpg",
                            Language = "ja",
                            Length = 100,
                            ReleaseDate = "2020-12-25",
                            Title = "Pokémon the Movie: Secrets of the Jungle"
                        },
                        new
                        {
                            Id = 14,
                            AgeRestriction = 0,
                            Description = "When Lois Lane is killed, an unhinged Superman decides to take control of the Earth. Determined to stop him, Batman creates a team of freedom-fighting heroes. But when superheroes go to war, can the world survive?",
                            Image = "https://image.tmdb.org/t/p/w500/lNRdCfVcjLs2LhO1Vb5rgnHV4JW.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-10-09",
                            Title = "Injustice"
                        },
                        new
                        {
                            Id = 15,
                            AgeRestriction = 0,
                            Description = "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
                            Image = "https://image.tmdb.org/t/p/w500/3WfvjNWr5k1Zzww81b3GWc8KQhb.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-09-01",
                            Title = "After We Fell"
                        },
                        new
                        {
                            Id = 16,
                            AgeRestriction = 0,
                            Description = "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.",
                            Image = "https://image.tmdb.org/t/p/w500/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg",
                            Language = "ru",
                            Length = 100,
                            ReleaseDate = "2021-01-01",
                            Title = "The Last Warrior: Root of Evil"
                        },
                        new
                        {
                            Id = 17,
                            AgeRestriction = 0,
                            Description = "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
                            Image = "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-09-01",
                            Title = "Shang-Chi and the Legend of the Ten Rings"
                        },
                        new
                        {
                            Id = 18,
                            AgeRestriction = 0,
                            Description = "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
                            Image = "https://image.tmdb.org/t/p/w500/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-07-28",
                            Title = "The Suicide Squad"
                        },
                        new
                        {
                            Id = 19,
                            AgeRestriction = 0,
                            Description = "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
                            Image = "https://image.tmdb.org/t/p/w500/uWStkK8bq9ixY3fc7y209ZleCoF.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-07-01",
                            Title = "The Boss Baby: Family Business"
                        },
                        new
                        {
                            Id = 20,
                            AgeRestriction = 0,
                            Description = "In the year 2524, four centuries after humans started colonizing the outer planets, retired General James Ford gets called back into service when a hostile alien fleet attacks soldiers on a remote planet. The threat against mankind soon escalates into an interstellar war as Ford and a team of elite soldiers try to stop the imminent attack before it's too late.",
                            Image = "https://image.tmdb.org/t/p/w500/6Wm7P6y22UZA40QuPYHyWyJ6leI.jpg",
                            Language = "en",
                            Length = 100,
                            ReleaseDate = "2021-03-12",
                            Title = "Cosmic Sin"
                        });
                });

            modelBuilder.Entity("MovieDbLib.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("presentation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RoomId = 1,
                            StartTime = "25.10.2021 00:00:00"
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            RoomId = 2,
                            StartTime = "26.10.2021 00:00:00"
                        });
                });

            modelBuilder.Entity("MovieDbLib.Entities.Presentation", b =>
                {
                    b.HasOne("MovieDbLib.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
